/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AccountSignUpRouteImport } from './routes/account.sign-up'
import { Route as AccountSignInRouteImport } from './routes/account.sign-in'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated.account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated.account.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminQuotationsRouteImport } from './routes/_authenticated.admin.quotations'
import { Route as AuthenticatedAdminProfileRouteImport } from './routes/_authenticated.admin.profile'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated.admin.payments'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated.admin.orders'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated.admin.feedback'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated.admin.categories'
import { Route as AuthenticatedAccountWishlistRouteImport } from './routes/_authenticated.account.wishlist'
import { Route as AuthenticatedAccountShipmentsRouteImport } from './routes/_authenticated.account.shipments'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated.account.profile'
import { Route as AuthenticatedAccountPaymentsRouteImport } from './routes/_authenticated.account.payments'
import { Route as AuthenticatedAccountInquiriesRouteImport } from './routes/_authenticated.account.inquiries'
import { Route as AuthenticatedAccountDocumentsRouteImport } from './routes/_authenticated.account.documents'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated.admin.products.index'
import { Route as AuthenticatedAccountOrdersIndexRouteImport } from './routes/_authenticated.account.orders.index'
import { Route as AuthenticatedAdminProductsNewRouteImport } from './routes/_authenticated.admin.products.new'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated.admin.products.$id'
import { Route as AuthenticatedAdminOrdersIdRouteImport } from './routes/_authenticated.admin.orders.$id'
import { Route as AuthenticatedAccountOrdersIdRouteImport } from './routes/_authenticated.account.orders.$id'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSignUpRoute = AccountSignUpRouteImport.update({
  id: '/account/sign-up',
  path: '/account/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSignInRoute = AccountSignInRouteImport.update({
  id: '/account/sign-in',
  path: '/account/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminQuotationsRoute =
  AuthenticatedAdminQuotationsRouteImport.update({
    id: '/quotations',
    path: '/quotations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfileRoute =
  AuthenticatedAdminProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAccountWishlistRoute =
  AuthenticatedAccountWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountShipmentsRoute =
  AuthenticatedAccountShipmentsRouteImport.update({
    id: '/shipments',
    path: '/shipments',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountPaymentsRoute =
  AuthenticatedAccountPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountInquiriesRoute =
  AuthenticatedAccountInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountDocumentsRoute =
  AuthenticatedAccountDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAccountOrdersIndexRoute =
  AuthenticatedAccountOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminProductsNewRoute =
  AuthenticatedAdminProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/products/$id',
    path: '/products/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersIdRoute =
  AuthenticatedAdminOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminOrdersRoute,
  } as any)
const AuthenticatedAccountOrdersIdRoute =
  AuthenticatedAccountOrdersIdRouteImport.update({
    id: '/orders/$id',
    path: '/orders/$id',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/account/sign-in': typeof AccountSignInRoute
  '/account/sign-up': typeof AccountSignUpRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/documents': typeof AuthenticatedAccountDocumentsRoute
  '/account/inquiries': typeof AuthenticatedAccountInquiriesRoute
  '/account/payments': typeof AuthenticatedAccountPaymentsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/shipments': typeof AuthenticatedAccountShipmentsRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/quotations': typeof AuthenticatedAdminQuotationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/account/orders/$id': typeof AuthenticatedAccountOrdersIdRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/account/orders/': typeof AuthenticatedAccountOrdersIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/account/sign-up': typeof AccountSignUpRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/documents': typeof AuthenticatedAccountDocumentsRoute
  '/account/inquiries': typeof AuthenticatedAccountInquiriesRoute
  '/account/payments': typeof AuthenticatedAccountPaymentsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/shipments': typeof AuthenticatedAccountShipmentsRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/quotations': typeof AuthenticatedAdminQuotationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/account/orders/$id': typeof AuthenticatedAccountOrdersIdRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/account/orders': typeof AuthenticatedAccountOrdersIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/account/sign-in': typeof AccountSignInRoute
  '/account/sign-up': typeof AccountSignUpRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_authenticated/account/documents': typeof AuthenticatedAccountDocumentsRoute
  '/_authenticated/account/inquiries': typeof AuthenticatedAccountInquiriesRoute
  '/_authenticated/account/payments': typeof AuthenticatedAccountPaymentsRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/shipments': typeof AuthenticatedAccountShipmentsRoute
  '/_authenticated/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/_authenticated/admin/quotations': typeof AuthenticatedAdminQuotationsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/account/orders/$id': typeof AuthenticatedAccountOrdersIdRoute
  '/_authenticated/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/_authenticated/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/_authenticated/account/orders/': typeof AuthenticatedAccountOrdersIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/account'
    | '/admin'
    | '/account/sign-in'
    | '/account/sign-up'
    | '/product/$slug'
    | '/account/documents'
    | '/account/inquiries'
    | '/account/payments'
    | '/account/profile'
    | '/account/shipments'
    | '/account/wishlist'
    | '/admin/categories'
    | '/admin/feedback'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/quotations'
    | '/admin/users'
    | '/account/'
    | '/admin/'
    | '/account/orders/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/account/sign-in'
    | '/account/sign-up'
    | '/product/$slug'
    | '/account/documents'
    | '/account/inquiries'
    | '/account/payments'
    | '/account/profile'
    | '/account/shipments'
    | '/account/wishlist'
    | '/admin/categories'
    | '/admin/feedback'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/quotations'
    | '/admin/users'
    | '/account'
    | '/admin'
    | '/account/orders/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/account/sign-in'
    | '/account/sign-up'
    | '/product/$slug'
    | '/_authenticated/account/documents'
    | '/_authenticated/account/inquiries'
    | '/_authenticated/account/payments'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/shipments'
    | '/_authenticated/account/wishlist'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/profile'
    | '/_authenticated/admin/quotations'
    | '/_authenticated/admin/users'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/_authenticated/account/orders/$id'
    | '/_authenticated/admin/orders/$id'
    | '/_authenticated/admin/products/$id'
    | '/_authenticated/admin/products/new'
    | '/_authenticated/account/orders/'
    | '/_authenticated/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRoute
  AccountSignInRoute: typeof AccountSignInRoute
  AccountSignUpRoute: typeof AccountSignUpRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/sign-up': {
      id: '/account/sign-up'
      path: '/account/sign-up'
      fullPath: '/account/sign-up'
      preLoaderRoute: typeof AccountSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/sign-in': {
      id: '/account/sign-in'
      path: '/account/sign-in'
      fullPath: '/account/sign-in'
      preLoaderRoute: typeof AccountSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quotations': {
      id: '/_authenticated/admin/quotations'
      path: '/quotations'
      fullPath: '/admin/quotations'
      preLoaderRoute: typeof AuthenticatedAdminQuotationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profile': {
      id: '/_authenticated/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthenticatedAdminProfileRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/wishlist': {
      id: '/_authenticated/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AuthenticatedAccountWishlistRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/shipments': {
      id: '/_authenticated/account/shipments'
      path: '/shipments'
      fullPath: '/account/shipments'
      preLoaderRoute: typeof AuthenticatedAccountShipmentsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/payments': {
      id: '/_authenticated/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AuthenticatedAccountPaymentsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/inquiries': {
      id: '/_authenticated/account/inquiries'
      path: '/inquiries'
      fullPath: '/account/inquiries'
      preLoaderRoute: typeof AuthenticatedAccountInquiriesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/documents': {
      id: '/_authenticated/account/documents'
      path: '/documents'
      fullPath: '/account/documents'
      preLoaderRoute: typeof AuthenticatedAccountDocumentsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/orders/': {
      id: '/_authenticated/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AuthenticatedAccountOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/products/new': {
      id: '/_authenticated/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AuthenticatedAdminProductsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders/$id': {
      id: '/_authenticated/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAdminOrdersRoute
    }
    '/_authenticated/account/orders/$id': {
      id: '/_authenticated/account/orders/$id'
      path: '/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AuthenticatedAccountOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountDocumentsRoute: typeof AuthenticatedAccountDocumentsRoute
  AuthenticatedAccountInquiriesRoute: typeof AuthenticatedAccountInquiriesRoute
  AuthenticatedAccountPaymentsRoute: typeof AuthenticatedAccountPaymentsRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountShipmentsRoute: typeof AuthenticatedAccountShipmentsRoute
  AuthenticatedAccountWishlistRoute: typeof AuthenticatedAccountWishlistRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAccountOrdersIdRoute: typeof AuthenticatedAccountOrdersIdRoute
  AuthenticatedAccountOrdersIndexRoute: typeof AuthenticatedAccountOrdersIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountDocumentsRoute: AuthenticatedAccountDocumentsRoute,
  AuthenticatedAccountInquiriesRoute: AuthenticatedAccountInquiriesRoute,
  AuthenticatedAccountPaymentsRoute: AuthenticatedAccountPaymentsRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountShipmentsRoute: AuthenticatedAccountShipmentsRoute,
  AuthenticatedAccountWishlistRoute: AuthenticatedAccountWishlistRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAccountOrdersIdRoute: AuthenticatedAccountOrdersIdRoute,
  AuthenticatedAccountOrdersIndexRoute: AuthenticatedAccountOrdersIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminOrdersRouteChildren {
  AuthenticatedAdminOrdersIdRoute: typeof AuthenticatedAdminOrdersIdRoute
}

const AuthenticatedAdminOrdersRouteChildren: AuthenticatedAdminOrdersRouteChildren =
  {
    AuthenticatedAdminOrdersIdRoute: AuthenticatedAdminOrdersIdRoute,
  }

const AuthenticatedAdminOrdersRouteWithChildren =
  AuthenticatedAdminOrdersRoute._addFileChildren(
    AuthenticatedAdminOrdersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRouteWithChildren
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProfileRoute: typeof AuthenticatedAdminProfileRoute
  AuthenticatedAdminQuotationsRoute: typeof AuthenticatedAdminQuotationsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminProductsNewRoute: typeof AuthenticatedAdminProductsNewRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRouteWithChildren,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProfileRoute: AuthenticatedAdminProfileRoute,
  AuthenticatedAdminQuotationsRoute: AuthenticatedAdminQuotationsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
  AuthenticatedAdminProductsNewRoute: AuthenticatedAdminProductsNewRoute,
  AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  AccountSignInRoute: AccountSignInRoute,
  AccountSignUpRoute: AccountSignUpRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
